### ISSUE TITLE
Error while flexmonster create angular -r

### ISSUE THREAD

**Issue by gssspillai** [flexmonster/pivot-angular#20]
4965 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
4966 verbose node v16.6.2
4967 verbose npm  v7.20.6
4968 error code 1
4969 error path /home/mysys/flexmonster/flexmonster-angular-project/node_modules/node-sass
4970 error command failed
4971 error command sh -c node scripts/build.js
4972 error Building: /usr/local/bin/node /home/mysys/flexmonster/flexmonster-angular-project/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

**Comment by VeraDidenko** [comment]
Hello, @gssspillai,

 

Thank you for reaching out to us and for providing the log output.


According to the log output, this seems to be a compatibility issue with `node-gyp` and the used node version rather than the sample Angular project. 
We managed to resolve the issue on our end by going back to [the latest stable release of Node.js (v14.17.5)](https://nodejs.org/en/).
Also, removing the `package-lock.json` file and rerunning npm install could help since the `package-lock.json` file was created with an older version of `npm`.

 

In addition, you are welcome to check out the following resources for more details on possible solutions: 

- [https://github.com/nodejs/node-gyp/tree/master/docs](https://github.com/nodejs/node-gyp/tree/master/docs)
- [https://www.flexmonster.com/question/flexmonster-create-angular-r-error/](https://www.flexmonster.com/question/flexmonster-create-angular-r-error/)

 

We hope this helps.

 

Kind regards,
Vera

**Comment by gssspillai** [comment]
Reinstalling Node LTS worked fine for me(In Ubuntu). Thank you @VeraDidenko

**Comment by VeraDidenko** [comment]
Hello, @gssspillai,

Thank you for the update. Glad to hear everything works!

Kind regards,
Vera
